# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
#To Create an array of 10 zeros, we can use zeros func to do so
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
#To Create an array of 10 ones, we can use ones func to do so
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
#To Create an array of 10 fives, we can use full to do so
five = np.full(10, 5.)
five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [10]:
#To create an array of the integers from 10 to 50, we can use arange func
fis = np.arange(10, 51)
fis
#Note that, you have to add 51 not 50, as it will not include it.
#So, in this case, I have used from 10 as it will include it, and 51 as it will not include it, it will stop at 50,
#as the question asked.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [13]:
#To create an array of all the even integers from 10 to 50, we can also use arange func
even = np.arange(10, 52, 2)
even
#Here, what I did is that, first I put the start 10, then the end which is 52 as we want the even num, then the step 2 to 
#move 2 each time to get the even num.

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##find the memory size of any array

In [15]:
#To get the size we can use nbytes to do so
even.nbytes

84

In [16]:
print(f'The memory size of the array is: {even.nbytes}')

The memory size of the array is: 84


#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
#To Create a 3x3 matrix with values ranging from 0 to 8, first I am going to create an array from the range 0 to 9 as the end 
#is not included, then taking it and make it to be a 3 * 3 matrix by using the reshape func
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [20]:
#To Create a 3x3 identity matrix, we can use the func eye to do so, and passing 3 in it
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [27]:
#to generate a random number between 0 and 1, we can use the random func to do so
np.random.random()

0.32019499321174805

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [29]:
#To generate an array of 25 random numbers sampled from a standard normal distribution, we can use randn func
np.random.randn(25)

array([-9.04292183e-02,  2.54154659e-01,  4.11380865e-01, -6.18183568e-01,
       -2.73233445e+00,  2.83148853e+00, -1.25896719e-01,  1.35515270e+00,
        1.89083426e+00, -3.33112271e-01,  1.91133512e+00, -1.36143981e+00,
       -1.43534574e-01, -2.32187680e-03, -1.10175084e-01,  1.37752123e-01,
       -2.15591286e+00,  4.74608731e-01, -1.03554570e-01,  2.73906081e-01,
        8.30672466e-02, -1.21423376e+00, -3.82027749e-01, -7.51170145e-01,
        7.16333558e-01])

#### Create the following matrix:

In [31]:
#We can use arange and reshape to create this matrix
m = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
m

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [35]:
#To Create an array of 20 linearly spaced points between 0 and 1, we can use the fun linspace and pass 0 for the begining
#1 for the end, and 20 for the num of values in it
lin = np.linspace(0, 1, 20)
lin

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [36]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [38]:
#To get the result we want, first we will use slicing for the index, the value we want starts from the 
#2 row as it starts from 0, then we want the index 1 from it which is 12, so, we gonna pass it
#Then put nothing after :, so it will give all the others followed it
rep1 = mat[2:, 1:]
rep1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
#To get the expected result, we can do the following, passing 3 as our 20 value is in the 3 row, and 
#in that row, 20 is in 4 index, so we pass it to get the result
rep2 = mat[3, 4]
rep2

20

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [48]:
#To get the result, we can get first all the ones that starts at the index 1, and stop at it, so I put 2, as it will not 
#include it, then we want all the 3 first ones from each one, so, I am put 3, as the index starts from 0
rep3 = mat[:3, 1:2]
rep3

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [51]:
#To get the result we want, I am going to take the row 5, and it is 4 in the indexing, so pass it first, then put :, to make
#it to take all the others to the end.
rep4 = mat[4:]
rep4

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
#To ge the result we want, I am going to start from the index 3 as our first one starts from there,
#Then put :, to take it to the end
rep5 = mat[3:]
rep5

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [53]:
#To get the sum of mat, we can use the fun sum to do so
mat.sum()

325

325

#### Get the standard deviation of the values in mat

In [55]:
#To get the standard deviation of the values in mat, we can use std fun to do so
mat.std()

7.211102550927978

7.211102550927978

#### Get the sum of all the columns in mat

In [56]:
#To get the sum of all the columns in mat, we can use sum func and pass mat and putting the axis 0
sum_col = np.sum(mat, axis=0)
sum_col 

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

####Create a 10*10  matrix with 1 on the border and 0 inside

In [58]:
#To get the expected result, I will start by creating a matrix with zeros func and pass 10, 10 to it
ten_m = np.zeros((10, 10))
ten_m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
#Then, I want to make the start and end to be filled with 1
ten_m[0, :] = 1 #This to fill the start
ten_m[-1, :] = 1 #This to fill the end
ten_m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
#Next, I am going to fill the borders with 1, on the left and on the right as well
#We can do the reverse of the above one
ten_m[:, 0] = 1 #This to fill the left
ten_m[:, -1] = 1 #This to fill the right
ten_m
#And this will give us the result we want

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### find common values between two arrays

In [65]:
x1 = np.array([0, 2, 2, 2, 4, 5, 1, 4, 8, 5])
x2 = np.array([2, 2, 3, 4, 7, 4, 6, 9, 4, 8])

In [68]:
#To find common values between two arrays, we can use intersect1d fun to do so
common = np.intersect1d(x1, x2)
print(common)

[2 4 8]


[2 4 8]


####You can use flatten to flatten your array into a 1D array

In [69]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [71]:
#To get the expected result, we can use flatten to do so.
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Great Job!